# Internet's second attempt
# always try to use HTTPS. I'm not sure why the nginx folks don't provide it.
- name: add 1password apt-key
  become: true
  apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    state: present

- name: add 1password apt repository
  become: true
  apt_repository:
    repo: "deb https://downloads.1password.com/linux/debian/amd64 stable main"
    state: present
    filename: 1password
    update_cache: yes

- name: install 1PasswordCLI
  become: true
  apt:
    name: ["1password-cli"]
    state: present
    update_cache: yes

- name: Lower the perms on ~/.config/op
  shell: chmod 700 /home/dockeruser/.config/op
# Internet first attempt
# - name: Check if 1password is installed
#   shell: which 1password
#   register: is_1password_installed_cmd
#   failed_when: false
# - name: set if 1password is available
#   set_fact:
#     is_1password_installed: "{{is_1password_installed_cmd.stdout != ''}}"

# - name: download 1password package
#   get_url:
#     url: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
#     dest: /tmp/1password-latest.deb
#   become: false
#   when: not is_1password_installed

# - name: install 1password
#   become: true
#   apt:
#     deb: /tmp/1password-latest.deb
#   when: not is_1password_installed

# My first attempt
# - name: Add 1password Apt repository key
#   shell: "curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg"
# - name: Add 1password Apt repository
#   shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" | sudo tee /etc/apt/sources.list.d/1password.list'
# - name: Add the debsig-verify policy
#   shell: "sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/ && curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol && sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22 && curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg"
# - name: Install 1PasswordCLI
#   apt:
#     name: ["1password-cli"]
