- name: Install pipx
  become: true
  pip:
    name: pipx
    state: latest

- name: Pipx ensure path
  shell: python3 -m pipx ensurepath

- name: Check if qqg is already installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/bin/qqg"
  register: qqg_file

- name: Install qqg
  get_url:
    url: https://github.com/emilkloeden/qqg-rs/releases/download/v1.0.0/qqg
    dest: "{{ lookup('env', 'HOME') }}/bin"
  tags:
    - install
    - tools
  when: not qqg_file.stat.exists

- name: Set execute permission on qqg
  file:
    path: "{{ lookup('env', 'HOME') }}/bin/qqg"
    mode: u+x

- name: Install md-browse
  community.general.pipx:
    name: md-browse
    python: "/usr/bin/python3.11"
    state: install
  tags:
    - install
    - tools
